### ISSUE TITLE
ApplicationDecorator instead of Draper

### ISSUE THREAD

**Issue by citizen428** [lockstep/rails_new#15]
Right now we're including Draper in the default `Gemfile`. However, as part of a recent discussion I came up with a pretty functional yet minimal decorator that could just be good enough™ and would remove a pretty big and magic external dependency:

```ruby
require 'forwardable'

class ApplicationDecorator
  extend Forwardable

  def self.forward_all
    define_method :method_missing do |m, *args, &block|
      return record.send(m, *args, &block) if record.respond_to?(m)
      super
    end

    define_method :respond_to_missing? do |m, include_private = false|
      record.respond_to?(m) || super(m, include_private)
    end
  end

  def self.forward(*methods)
    def_delegators :record, *methods
  end

  def self.forward_aliased(hash)
    hash.each do |old_name, new_name|
      def_delegator :record, old_name, new_name
    end
  end

  attr_reader :record

  def initialize(record)
    @record = record
  end
end
```

Example decorator (with a fake user object):

```ruby
require 'ostruct'
user = OpenStruct.new(first_name: 'Michael', last_name: "Kohl")

class UserDecorator < ApplicationDecorator
  include ActionView::Helpers::TagHelper

  forward_all

  def full_name
    content_tag :strong, "#{first_name} #{last_name}"
  end
end

du =. UserDecorator.new(user)
du.full_name
#=> "<strong>Michael Kohl</strong>"
```

As you can see this allows:  

1. forwarding all methods the wrapped record supports via `forward_all`.
2. forwarding selected methods via `forward`.
3. forwarding methods while renaming them via `forward_aliased`.
4. full access to the wrapped object via the `record` method.
5. integrating whichever helpers one needs via a basic `include` call (no magic)

This was a ~20 minute hack, but I think it's rather promising. If we can agree to replace Draper I'd spend some more time on this and also add tests etc.

**Comment by hiattp** [comment]
Cool, fine with me. I generally assume draper is doing something similar but yeah we probably don't need any of its fluff

**Comment by janklimo** [comment]
Nice one @citizen428 👍  I recently watched a Design patterns in Ruby course and he uses `forwardable` for decorators as well.

I'm wondering what's the motivation behind it? Is Draper famous for being inefficient at something? I'd be worried about losing the handy stuff that comes with Draper (e.g. collections, any edge-cases handling?), so we'd have to keep adding/fixing them ourselves whenever there is need for them. I'm also wondering if it's easier to google Draper-related queries than finding answers to decorators as a design pattern (thinking about new developers joining a project).

**Comment by citizen428** [comment]
@hiattp It does something similar, with layers and layers of Ruby magic on top.

@janklimo I had several motivations (not just "not invented here syndrome" 😉 ): 

* Reduce the number of gems we depend on. Draper ties surprisingly deeply into Rails, so it was actually one of the last gems in our template app that released a version for Rails 5.
* Draper assumes the only thing you'd ever want to decorate is an AR instance, whereas the pattern is useful in many other cases too (wrapping objects you don't control for example or as alternative to monkey patching). 
* For every decorator instance you also instantiate a `view_context`, so Draper can magically make it available in their `h` helper. This seems wasteful when you can just include the helper(s) you need.
* The use of the magic `decorate` method makes it hard to see where exactly certain decorators are used (i.e. `@article.decorate` or `Article.find(params[:id]).decorate` vs `ArticleDecorator.new(@article)`).

Regarding your concerns: I don't think that it's necessary to google for "answers to decorators as a design pattern", this simple class above should arguable be easier to understand than Draper. It also essentially works like `ActiveModel::Serializers` (specify things you want forwarded, add your own methods for the rest), so most people joining a Rails project should get it.  Plus if you ever feel like you have more complex needs it's easy to add Draper and delete this one file. 

Anyway, I don't quite have the time right now to add all the necessary tests etc.

**Comment by janklimo** [comment]
@citizen428 good points 👍  makes a lot of sense whenever there's time for it

**Comment by citizen428** [comment]
Closing, all follow-up discussion can happen in https://github.com/lockstep/rails_new/pull/17
