### ISSUE TITLE
Use Ruby 2.7

### ISSUE THREAD

**Issue by janklimo** [lockstep/rails_new#150]
I tried the upgrade and it [went well](https://circleci.com/gh/Verumex/verumex/7701). We could either upgrade now (and live with the deprecation warnings) or wait until a new Rails release which will fix 90% of them. Then we can fix the warnings originating from our code. There's also an option to [suppress them](https://dev.to/andrewmcodes/hiding-ruby-2-7-deprecation-warnings-in-rails-6-2mil). I'd prefer not to do that.

What are your thoughts on that @hiattp?

Notes:

- `pry-doc` in not 2.7-compatible but I don't think that's an issue

**Comment by hiattp** [comment]
Cool. Let's hold off a bit and do it with one of our bundle parties 👍

**Comment by janklimo** [comment]
Done 🎉
