### ISSUE TITLE
best practice for high voltage

### ISSUE THREAD

**Issue by hiattp** [lockstep/rails_new#34]
@citizen428 what is the best practice for adding high voltage pages? Looks like the routes are disabled by default and the pages will operate at the root, is the intent to add individual/explicit page routes for any high voltage pages?

**Comment by citizen428** [comment]
Tbh, I've never had much use for High Voltage in any other scenario than a top-level static page or two, so I'm by no means an expert on best practices. The [documentation](https://github.com/thoughtbot/high_voltage/blob/master/README.md) is pretty good though and I'm open to any suggestions/PRs others might have on this topic.

**Comment by hiattp** [comment]
Oh ok I thought you had a pattern here that you preferred. I’ve never really used high voltage that much either... I’m wondering if we should just pull it out? I’m not sure the extra magic is worth it for an occasional static page, if we are going to add our own routes it seems like we are only saving the effort of creating a static page controller (but that has the advantage of being explicit/conventional). Thoughts?

**Comment by citizen428** [comment]
Sure, we can do that.

**Comment by janklimo** [comment]
@citizen428 should we close this?
