### ISSUE TITLE
Upgrade to CircleCI 2.0

### ISSUE THREAD

**Issue by janklimo** [lockstep/rails_new#49]
After August 31, 2018, CircleCI 1.0 will [no longer be available](https://circleci.com/blog/sunsetting-1-0/).

@hiattp @citizen428

**Comment by hiattp** [comment]
😢

**Comment by citizen428** [comment]
@janklimo Yes, @hiattp and I had already talked about that yesterday. I already made a branch for this once, but then we decided to stick with CircleCI 1.0 for the beginning. I'll resurrect that branch eventually.
